version: '3.8'

services:
  employee-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-api:1.0
    container_name: employ-management-api
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
